id: IFE1D6E9C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T17:34:56+00:00'
last_modified: '2022-06-08T12:10:19.356374+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN5011
  title: ཕོ་བྲང་པོ་ཏ་ལའི་ས་སྐྱའི་གསུང་རབ་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    DD27:
      image_group_id: I3CN8671
      title: ''
      total_pages: 658
      order: 1
      base_file: DD27.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
